config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'groups#index'

  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
  resources :users, only: [:index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  mount_uploader :image, ImageUploader
  validates :body, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:acount_update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
    @group = Group.find_by(params[:group_id])
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group), notice: 'グループを作成しました'
    else
      flash[:alert] = "グループ名を入力してください"
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), noice: 'グループを編集しました'
    else
      flash[:alert] = "グループ名を入力してください"
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_variables, only: [:index, :create]

  def index
    @message = Message.new
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json
      end
    else
      flash[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id, group_id: params[:group_id])
  end

  def set_variables
    @group = Group.find(params[:group_id])
    @messages = @group.messages.includes(:user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where.not(id: current_user.id).where('name LIKE ?', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      redirect_to :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatside_helper.rb
module ChatsideHelper

  def latest_message(group)
    group.messages.last
  end

  def latest_body(group)
    latest_message(group).body
  end

  def latest_image(group)
    latest_message(group).image
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
  def time(message)
    message.created_at.to_s(:jp)
  end
end

app/views/groups/_user.html.haml
.chat-group-user
  .chat-group-user__name
    = user.name
    = hidden_field_tag('group[user_ids][]', user.id)
  .chat-group-user__btn.chat-group-user__btn--remove
    削除

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group, remote: :true do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @group.errors.full_messages.each do |message|
            %li= message

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名",class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat-group_name chat-group-form__input', placeholder: 'グループ名を入力してください'

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :user_ids, "チャットメンバーを追加",class: 'chat-group-form__label'
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{ placeholder: "追加したいユーザー名を入力してください", type: "text" }
        #user-search-result

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :user_ids, "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user
            = current_user.name
            = f.hidden_field :user_ids, value: current_user.id, name: 'group[user_ids][]'
          = render partial: 'groups/user', collection: @group.users.where.not(id: current_user.id)

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class: 'chat-group-form__action-btn'

app/views/groups/index.html.haml
.chat-side

  = render 'layouts/chatside'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group, remote: :true do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @group.errors.full_messages.each do |message|
            %li= message

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名",class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat-group_name chat-group-form__input', placeholder: 'グループ名を入力してください'

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :user_ids, "チャットメンバーを追加",class: 'chat-group-form__label'
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{ placeholder: "追加したいユーザー名を入力してください", type: "text" }
        #user-search-result

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :user_ids, "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user
            = current_user.name
            = f.hidden_field :user_ids, value: current_user.id, name: 'group[user_ids][]'

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class: 'chat-group-form__action-btn'

app/views/layouts/_chatside.html.haml
.chat-side__user
  .chat-side__user-content
    %h4.chat-side__user-content-name
      = current_user.name
    = link_to new_group_path, class: "chat-side__user-content-new-group" do
      %i.fa.fa-pencil-square-o
    = link_to edit_user_registration_path, class: "chat-side__user-content--edit-user" do
      %i.fa.fa-cog

.chat-side__groups
  .chat-side__groups-list
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        .chat-side__group
          %p.chat-side__group-name
            = group.name
          %p.chat-side__group-message
            - if group.messages.present?
              - if latest_image(group).present?
                = "画像が投稿されています"
              - else
                = latest_body(group)
            - else
              = "まだメッセージはありません"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace2
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/_message.html.haml
%p.chat-main__message-name
  = message.user.name
%p.chat-main__message-time
  = time(message)
- if message.body.present?
  %p.chat-main__message-body
    = message.body
- if message.image.present?
  %p.chat-main__message-image
    = image_tag message.image

app/views/messages/index.html.haml
%body
  .chat-side
    = render 'layouts/chatside'

  .chat-main
    .chat-main__header
      .chat-main__header--group.clearfix
        %h4.chat-main__header--group-name
          = @group.name
        %a
          = link_to "edit", edit_group_path(params[:group_id]), class: 'chat-main__header--group-edit-btn'
      .chat-main__header-members
        MEMBER:
        %span.chat-main__header-members
          = @group.users.pluck(:name).join(", ")

    .chat-main__body
      .chat-main__body--messages-list
      .chat-main__message.clearfix#319
        = render @messages

    .chat-main__footer
      = form_for [@group, @message] do |f|
        .chat-main__footer-form
          .chat-main__footer-form__body
            = f.text_area :body, class: 'message', placeholder: 'type a message'
            = f.label :image, class: 'chat-file' do
              %i.fa.fa-image
              = f.file_field :image, class: 'image'
          = f.submit 'Send', class: 'submit'